### PR TITLE
fix: enforce lowercase on AtKey

### LINKED ISSUE #964: Review usage of encoding of keys in secondary store and toLowerCase in server
### Describe the bug

a) hive_keystore.dart put/create and delete methods use Utf7 encoding. 
Encoding is inconsistent while adding entry to metadataCache. See https://github.com/atsign-foundation/at_client_sdk/issues/742#issuecomment-1274406790
Review the usage of at keys encoding through out persistence and server code base.

b) secondary_util.dart convert command converts command part of at protocol command to lowercase. If an atsign/command has mixed case, analyse the impact

### Steps to reproduce

n/a

### Expected behavior

* encoding and lower case conversion should be consistent and well documented

### PR DESCRIPTION
**Pull request by srieteja**
closes https://github.com/atsign-foundation/at_server/issues/964
**- What I did**
- converted namespace in AtKey class to a private variable and introduced getters and setters for the same
- convert key to lower_case in AtKey.toString and all the other child key types
- enforcing toLowerCase() for all AtKey params in their respective setters
- set isHidden param of MetaData to true in PrivateKey class
- added isHidden check in AtKey.toString() to construct private keys when isHidden is set to true

**- How to verify it**
- testcases to assert the lower_case related changes added to test/at_key_test.dart

**- Description for the changelog**

- chore: AtKey.key and AtKey.namespace made private(get and set introduced) and enforcing toLowerCase() for all AtKey params in their respective setters

### CODE REVIEW

File: packages/at_commons/lib/src/keystore/at_key.dart [hunk 1]
```diff
@@ -38,22 +38,31 @@ class AtKey {
   /// These keys will never be synced between the client and secondary server.
   bool _isLocal = false;
 
+  String? get namespace => _namespace;
+
+  set namespace(String? namespace) {
+    if (namespace != null && namespace.isNotEmpty) {
```
Comment (sitaram-kalluri) [inline packages/at_commons/lib/src/keystore/at_key.dart]: Please replace the above IF conditions with "namespace.isNotNullOrEmpty" than having two checks.

Comment (srieteja) [reply packages/at_commons/lib/src/keystore/at_key.dart]: addressed as part of the last commit

**Review by murali-shris — APPROVED** [review]

**Review by sitaram-kalluri — APPROVED** [review]
